services:
  postgres:
    image: postgres:15
    container_name: formalizese-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3Q9Eg4EEZ54EY66d0ZkUGdqY
      POSTGRES_DB: formalizese
    command: >
      -c ssl=on
      -c ssl_cert_file=/certs/server.crt
      -c ssl_key_file=/certs/server.key
    ports:
      - "5432:5432"
    volumes:
      - formalizese_pg_data:/var/lib/postgresql/data
      - formalizese_pg_certs:/certs:ro
  localstack:
    image: localstack/localstack:4.4.0
    container_name: formalizese-localstack
    restart: unless-stopped
    environment:
      - SERVICES=s3,sqs
      - DEFAULT_REGION=sa-east-1
      - PERSISTENCE=1
    ports:
      - "4566:4566"
    volumes:
      - formalizese_localstack_data:/var/lib/localstack
volumes:
  formalizese_pg_data:
  formalizese_localstack_data:
  formalizese_pg_certs:
    external: true
